version: '2.3'
services:
  db:
    container_name: ${CONTAINER_DATABASE_NAME}
    image: mysql:5.7.23
    ports:
      - $DB_PORT
    volumes:
      - "${MYSQL_VOLUME}:/var/lib/mysql"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: unless-stopped
    networks:
      - default
  app:
    container_name: ${CONTAINER_APP_NAME}
    image: crazyfffan/koe:3.2
    networks:
      - default
      - web
    ports:
      - $EXPOSED_PORTS
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PROTO=uwsgi
      #     Uncomment below to DELETE and re-create the database from fixtures
      # - RESET_DB=true
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./user_data:/code/user_data
      - ./logs:/code/logs
      - ./backups:/code/backups
      - ./notebooks:/code/notebooks
      - ./settings:/code/settings
  cache:
    image: redis
    container_name: ${CONTAINER_CACHE_NAME}
    restart: unless-stopped
    networks:
      - default

networks:
  web:
    external:
      name: ${EXTERNAL_NETWORK}
